declare module '@env' {
  export const APPWRITE_ENDPOINT: string;
  export const APPWRITE_PROJECT_ID: string;
  export const APPWRITE_DATABASE_ID: string;
  export const APPWRITE_CATEGORY_COLLECTION_ID: string;
  export const APPWRITE_USER_PROFILES_COLLECTION_ID: string;
  export const APPWRITE_CONTENT_COLLECTION_ID: string;
  export const APPWRITE_SUPPORT_COLLECTION_ID: string;
  export const APPWRITE_SETTINGS_COLLECTION_ID: string;
  export const APPWRITE_INVITATIONS_COLLECTION_ID: string;
  export const APPWRITE_INVITATION_FUNCTION_ID: string;
  export const APPWRITE_WELCOME_QUOTE_COLLECTION_ID: string;
  export const APPWRITE_PLATFORM: string;
  export const APPWRITE_STORAGE_BUCKET_ID: string;
  export const IAP_PRODUCT_ID_MONTHLY: string;
  export const IAP_PRODUCT_ID_YEARLY: string;
  export const REVENUECAT_API_KEY: string;
  export const REVENUECAT_API_KEY_IOS: string;
  export const REVENUECAT_API_KEY_ANDROID: string;
}
